version: "2"
services:

    # PHP7-FPM container
    php:
        build:
            context: docker/php
            dockerfile: Dockerfile
        links:
            - mysql
        volumes:
            - ./:/var/www/

    # Nginx container
    nginx:
        image: nginx:1.10.0
        links:
            - php
        volumes:
            - ./docker/nginx/etc/conf.d/vhost.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

    # MySQL container
    mysql:
        image: mysql:5.6
        volumes:
            - ./var/mysql:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: root
